from __future__ import annotations

from dataclasses import replace
import json
from pathlib import Path
import tempfile
import unittest

from scripts.pipeline_executor import (
    PipelineExecutor,
    StepCompletionEvent,
    StepExecutionRequest,
    prepare_workflow_run,
)
from scripts.run_issue_workflow import (
    ImplementationReviewController,
    ReviewFinding,
    ReviewResult,
    WorkflowParityError,
    assert_workflow_parity,
    characterize_configured_requests,
    characterize_legacy_workflow,
    compare_workflow_characterization,
)
from scripts.workflow_config import (
    LoopConfig,
    StepConfig,
    build_artifact_namespace_plan,
    normalize_workflow_config,
    parse_workflow_config,
    validate_workflow_capabilities,
    default_capability_registry,
    preflight_workflow_bounds,
)


class CharacterizationPort:
    """A side-effect-limited fake port used by the parity harness."""

    def __init__(self, *, initial_review_status: str) -> None:
        self.initial_review_status = initial_review_status
        self.requests: list[StepExecutionRequest] = []

    def execute(self, request: StepExecutionRequest) -> object:
        self.requests.append(request)
        for output in request.expected_outputs:
            output.path.parent.mkdir(parents=True, exist_ok=True)
            if output.id == "review":
                status = (
                    self.initial_review_status
                    if request.step.local_id == "implementation_reviewer_initial"
                    else "no_findings"
                )
                findings = (
                    (ReviewFinding(id="F-001", description="Repair this"),)
                    if status == "findings_present"
                    else ()
                )
                output.path.write_text(
                    json.dumps(
                        {
                            "schema_version": "1.0",
                            "status": status,
                            "findings": [
                                {"id": finding.id, "description": finding.description}
                                for finding in findings
                            ],
                        }
                    )
                    + "\n",
                    encoding="utf-8",
                )
            else:
                output.path.write_text(
                    f"generated by {request.node_instance_id}\n",
                    encoding="utf-8",
                )

        if request.step.local_id.startswith("implementation_reviewer"):
            status = (
                self.initial_review_status
                if request.step.local_id == "implementation_reviewer_initial"
                else "no_findings"
            )
            findings = (
                (ReviewFinding(id="F-001", description="Repair this"),)
                if status == "findings_present"
                else ()
            )
            canonical_findings = (
                '{"findings":[{"description":"Repair this","id":"F-001"}],'
                '"schema_version":"1.0"}'
                if findings
                else '{"findings":[],"schema_version":"1.0"}'
            )
            return StepCompletionEvent(
                result=ReviewResult(
                    schema_version="1.0",
                    status=status,
                    findings=findings,
                    canonical_findings_json=canonical_findings,
                )
            )
        return None


class WorkflowCompatibilityTests(unittest.TestCase):
    repository_root = Path(__file__).resolve().parents[1]
    planning_config_path = repository_root / "workflows" / "issue-v1.json"
    execution_config_path = repository_root / "workflows" / "issue-v1-execution.json"

    def load_standard_config(self):
        """Build the old one-run shape only as a parity-test oracle.

        Production CLI execution is intentionally split into two configs.  The
        legacy characterization tests still need one in-memory plan so they
        can compare the combined lifecycle event stream with the fixed
        workflow without reintroducing a monolithic production config.
        """
        planning = json.loads(self.planning_config_path.read_text(encoding="utf-8"))
        execution = json.loads(self.execution_config_path.read_text(encoding="utf-8"))
        combined = dict(planning)
        combined_nodes = list(planning["nodes"]) + list(execution["nodes"])
        implementation = combined_nodes[6]
        assert isinstance(implementation, dict)
        source = implementation["source"]
        assert isinstance(source, dict)
        source["from"] = "artifact:work_breakdown.work_items"
        combined["nodes"] = combined_nodes
        return parse_workflow_config(combined)

    def prepare_standard(self, artifact_root: Path, items: list[dict[str, object]]):
        config = self.load_standard_config()
        authorization = validate_workflow_capabilities(
            config,
            default_capability_registry(),
            repo_root=self.repository_root,
        )
        bounds = preflight_workflow_bounds(
            normalize_workflow_config(config),
            {"kelpie.work_items.v1": items},
            registry=authorization.snapshot,
        )
        namespaces = build_artifact_namespace_plan(
            normalize_workflow_config(config),
            bounds,
            artifact_root=artifact_root,
            item_namespace="work-items",
        )
        prepared = prepare_workflow_run(
            config,
            repo_root=self.repository_root,
            artifact_root=artifact_root,
            providers={"kelpie.work_items.v1": items},
            item_namespace="work-items",
            issue_snapshot={"number": 20},
            repo_instructions_snapshot="repository instructions",
        )
        self.assertEqual(namespaces.entries, prepared.artifact_namespaces.entries)
        return prepared

    def execute_standard(
        self,
        *,
        items: list[dict[str, object]],
        initial_review_status: str,
    ):
        with tempfile.TemporaryDirectory() as tmpdir:
            artifact_root = Path(tmpdir) / "artifacts"
            prepared = self.prepare_standard(artifact_root, items)
            port = CharacterizationPort(initial_review_status=initial_review_status)
            result = PipelineExecutor(
                port,
                virtual_inputs={
                    "$issue": {"number": 20},
                    "$repo_instructions": "repository instructions",
                },
                controllers={
                    "implementation_review_v1": ImplementationReviewController(
                        registry=prepared.capability_authorization.snapshot,
                    )
                },
            ).execute(prepared)
            self.assertTrue(result.succeeded, result.error)
            configured = characterize_configured_requests(
                result.requests,
                artifact_root=artifact_root,
            )
            legacy = characterize_legacy_workflow(
                artifact_root,
                item_ids=[str(item["id"]) for item in items],
                review_status=initial_review_status,
            )
            return result, port, legacy, configured

    def test_standard_config_declares_nine_phases_and_implementation_roles(self) -> None:
        config = self.load_standard_config()
        top_steps = [node for node in config.nodes if isinstance(node, StepConfig)]
        loops = [node for node in config.nodes if isinstance(node, LoopConfig)]

        self.assertEqual(
            [step.id for step in top_steps],
            [
                "prototype_planning",
                "prototyping",
                "red_team_review",
                "solution_design",
                "work_breakdown",
                "plan_comprehension_check",
                "review_fix_loop",
                "pull_request",
            ],
        )
        self.assertEqual(len(loops), 1)
        implementation = loops[0]
        self.assertEqual(implementation.id, "implementation")
        self.assertEqual(
            [step.id for step in implementation.body],
            [
                "implementation_coder",
                "implementation_reviewer_initial",
                "implementation_fix",
                "implementation_reviewer_final",
            ],
        )
        self.assertEqual(
            [step.lifecycle for step in implementation.body],
            [
                "kelpie.phase.implementation_coder.v1",
                "kelpie.phase.implementation_reviewer.v1",
                "kelpie.phase.implementation_fix.v1",
                "kelpie.phase.implementation_reviewer.v1",
            ],
        )
        self.assertEqual(implementation.source.source, "artifact:work_breakdown.work_items")

    def test_clean_implementation_route_matches_legacy_order_and_contract(self) -> None:
        result, port, legacy, configured = self.execute_standard(
            items=[{"id": "WB-01"}, {"id": "WB-09"}],
            initial_review_status="no_findings",
        )
        self.assertEqual(len(port.requests), 12)
        self.assertEqual(
            [request.node_instance_id for request in port.requests[:6]],
            [
                "nodes/prototype_planning",
                "nodes/prototyping",
                "nodes/red_team_review",
                "nodes/solution_design",
                "nodes/work_breakdown",
                "nodes/plan_comprehension_check",
            ],
        )
        self.assertEqual(
            [request.loop_context.item_id for request in port.requests[6:-2]],
            ["WB-01", "WB-01", "WB-09", "WB-09"],
        )
        self.assertEqual(
            [request.node_instance_id for request in port.requests[-2:]],
            ["nodes/review_fix_loop", "nodes/pull_request"],
        )
        report = compare_workflow_characterization(legacy, configured)
        self.assertTrue(report.matches, report.differences)
        self.assertEqual(
            configured[0].lifecycle_stages,
            ("pre", "execute", "post_action", "post_check", "outcome"),
        )
        self.assertIn("pause", configured[0].outcome_decisions)
        self.assertEqual(
            {
                event.artifact_scope
                for event in configured
                if event.phase == "implementation"
            },
            {
                "work-items/WB-01/iterations/0000/coder",
                "work-items/WB-01/iterations/0000/reviewer",
                "work-items/WB-09/iterations/0000/coder",
                "work-items/WB-09/iterations/0000/reviewer",
            },
        )
        self.assertTrue(result.succeeded)

    def test_fix_route_matches_legacy_lifecycle_and_artifact_contract(self) -> None:
        _result, port, legacy, configured = self.execute_standard(
            items=[{"id": "WB-09"}],
            initial_review_status="findings_present",
        )
        self.assertEqual(
            [request.node_instance_id for request in port.requests[-6:-2]],
            [
                "nodes/implementation/body/implementation_coder@WB-09",
                "nodes/implementation/body/implementation_reviewer_initial@WB-09",
                "nodes/implementation/body/implementation_fix@WB-09",
                "nodes/implementation/body/implementation_reviewer_final@WB-09",
            ],
        )
        report = compare_workflow_characterization(legacy, configured)
        self.assertTrue(report.matches, report.differences)
        fix_request = next(
            request
            for request in port.requests
            if request.step.local_id == "implementation_fix"
        )
        self.assertEqual(
            fix_request.resolved_inputs[1].source,
            "item-artifact:implementation_reviewer_initial.review",
        )
        self.assertEqual(
            fix_request.resolved_inputs[1].artifacts[0].namespace.relative_path,
            "work-items/WB-09/iterations/0000/reviewer/review-result.json",
        )

    def test_parity_failure_is_an_explicit_gate_without_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            legacy = characterize_legacy_workflow(
                Path(tmpdir),
                item_ids=["WB-09"],
            )
            changed = tuple(
                replace(event, runner="different-runner")
                if event.node_instance_id == "nodes/work_breakdown"
                else event
                for event in legacy
            )
            report = compare_workflow_characterization(legacy, changed)

        self.assertFalse(report.matches)
        self.assertTrue(
            any(
                difference.startswith("event[4] runner differs:")
                for difference in report.differences
            )
        )
        with self.assertRaises(WorkflowParityError):
            assert_workflow_parity(legacy, changed)


if __name__ == "__main__":
    unittest.main()
