"""Cross-cutting acceptance coverage for the Issue #20 workflow boundary.

The lower-level workflow tests exercise individual loader, graph, bounds,
artifact, executor, and CLI behaviors.  This module keeps the Issue's
acceptance criteria visible at the integration boundary:

* configuration alone changes the declared execution order;
* top-level and loop-body steps use one request contract;
* invalid configurations fail before a port or artifact root is reached;
* the bundled workflow remains characteristically compatible with the fixed
  workflow; and
* runner command resolution remains outside the declarative workflow.
"""

from __future__ import annotations

from copy import deepcopy
import json
from pathlib import Path
import tempfile
import unittest

from scripts.pipeline_executor import (
    PipelineExecutor,
    StepCompletionEvent,
    StepExecutionRequest,
    prepare_workflow_run,
)
from scripts.run_issue_workflow import (
    ImplementationReviewController,
    ReviewResult,
    RunnerConfig,
    RunnerResolver,
    RunnerResolverCapabilityAdapter,
    assert_workflow_parity,
    characterize_configured_requests,
    characterize_legacy_workflow,
)
from scripts.workflow_config import (
    LoopConfig,
    StepConfig,
    WorkflowConfigError,
    default_capability_registry,
    load_workflow_config,
    parse_workflow_config,
)


class RecordingAcceptancePort:
    """A bounded fake port that materializes declared file outputs."""

    def __init__(self) -> None:
        self.requests: list[StepExecutionRequest] = []

    def execute(self, request: StepExecutionRequest) -> StepCompletionEvent:
        self.requests.append(request)
        for output in request.expected_outputs:
            output.path.parent.mkdir(parents=True, exist_ok=True)
            if output.kind == "directory":
                output.path.mkdir(parents=True, exist_ok=True)
            elif output.id == "review":
                output.path.write_text(
                    json.dumps(
                        {
                            "schema_version": "1.0",
                            "status": "no_findings",
                            "findings": [],
                        }
                    )
                    + "\n",
                    encoding="utf-8",
                )
            else:
                output.path.write_text(
                    f"generated by {request.node_instance_id}\n",
                    encoding="utf-8",
                )

        if request.step.local_id.startswith("implementation_reviewer"):
            return StepCompletionEvent(
                node_instance_id=request.node_instance_id,
                result=ReviewResult(
                    schema_version="1.0",
                    status="no_findings",
                    findings=(),
                    canonical_findings_json='{"findings":[],"schema_version":"1.0"}',
                ),
            )
        return StepCompletionEvent(node_instance_id=request.node_instance_id)


class WorkflowAcceptanceTests(unittest.TestCase):
    repository_root = Path(__file__).resolve().parents[1]
    valid_fixture = repository_root / "tests" / "fixtures" / "workflows" / "valid-v1.json"
    standard_config_path = repository_root / "workflows" / "issue-v1.json"
    execution_config_path = repository_root / "workflows" / "issue-v1-execution.json"

    def load_combined_compatibility_config(self):
        """Compose the two production stages for the legacy parity oracle."""
        planning = json.loads(self.standard_config_path.read_text(encoding="utf-8"))
        execution = json.loads(self.execution_config_path.read_text(encoding="utf-8"))
        combined = dict(planning)
        combined_nodes = list(planning["nodes"]) + list(execution["nodes"])
        implementation = combined_nodes[6]
        assert isinstance(implementation, dict)
        source = implementation["source"]
        assert isinstance(source, dict)
        source["from"] = "artifact:work_breakdown.work_items"
        combined["nodes"] = combined_nodes
        return parse_workflow_config(combined)

    @staticmethod
    def step(
        node_id: str,
        *,
        output_id: str | None = None,
        output_path: str | None = None,
        inputs: list[dict[str, str]] | None = None,
        depends_on: list[str] | None = None,
    ) -> dict[str, object]:
        outputs: list[dict[str, str]] = []
        if output_id is not None and output_path is not None:
            outputs.append({"id": output_id, "kind": "file", "path": output_path})
        return {
            "type": "step",
            "id": node_id,
            "lifecycle": "kelpie.phase.plan.v1",
            "runner": "codex",
            "prompt": "prompts/plan.md",
            "skill": "skills/plan.md",
            "inputs": inputs or [],
            "outputs": outputs,
            "depends_on": depends_on or [],
        }

    @classmethod
    def top_level_payload(cls, node_ids: tuple[str, ...]) -> dict[str, object]:
        return {
            "schema_version": "1.0",
            "id": "acceptance-workflow",
            "profile": "repository_issue",
            "limits": {},
            "nodes": [
                cls.step(
                    node_id,
                    output_id=f"{node_id}_output",
                    output_path=f"{node_id}.md",
                )
                for node_id in node_ids
            ],
        }

    @classmethod
    def loop_payload(cls) -> dict[str, object]:
        return {
            "schema_version": "1.0",
            "id": "acceptance-loop-workflow",
            "profile": "repository_issue",
            "limits": {"max_loop_items": 2, "max_total_steps": 10},
            "nodes": [
                cls.step(
                    "plan",
                    output_id="plan",
                    output_path="plan.md",
                    inputs=[{"name": "issue", "from": "$issue"}],
                ),
                {
                    "type": "loop",
                    "id": "implementation",
                    "source": {
                        "from": "artifact:plan",
                        "provider": "kelpie.work_items.v1",
                    },
                    "max_items": 2,
                    "controller": "fixed_sequence.v1",
                    "body": [
                        cls.step(
                            "coder",
                            output_id="notes",
                            output_path="notes.md",
                            inputs=[{"name": "item", "from": "$loop_item"}],
                        )
                    ],
                    "exports": [],
                },
            ],
        }

    @classmethod
    def write_resources(cls, root: Path) -> None:
        for relative in ("prompts/plan.md", "skills/plan.md"):
            path = root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(f"# {relative}\n", encoding="utf-8")

    @classmethod
    def prepare(
        cls,
        root: Path,
        payload: dict[str, object],
        *,
        items: list[dict[str, object]] | None = None,
    ):
        cls.write_resources(root)
        return prepare_workflow_run(
            parse_workflow_config(payload),
            repo_root=root,
            artifact_root=root / "artifacts",
            providers=(
                {"kelpie.work_items.v1": items}
                if items is not None
                else None
            ),
            issue_snapshot={"number": 20, "body": "acceptance"},
            repo_instructions_snapshot="# repository rules\n",
        )

    def test_config_only_add_remove_reorder_changes_execution_order(self) -> None:
        """AC-1: basic step changes require no Python workflow edit."""

        variants = (
            (("first", "second"), ("nodes/first", "nodes/second")),
            (
                ("third", "first", "second"),
                ("nodes/third", "nodes/first", "nodes/second"),
            ),
            (("second", "first"), ("nodes/second", "nodes/first")),
        )
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            for index, (node_ids, expected_order) in enumerate(variants):
                with self.subTest(node_ids=node_ids):
                    run_root = root / f"run-{index}"
                    run_root.mkdir()
                    port = RecordingAcceptancePort()
                    result = PipelineExecutor(
                        port,
                        virtual_inputs={"$issue": {"number": 20}},
                    ).execute(self.prepare(run_root, self.top_level_payload(node_ids)))

                    self.assertTrue(result.succeeded, result.error)
                    self.assertEqual(
                        tuple(request.node_instance_id for request in port.requests),
                        expected_order,
                    )

    def test_top_level_and_loop_steps_share_contract_and_item_namespaces(self) -> None:
        """AC-2/3/4: one request contract carries per-step and item data."""

        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            artifact_root = root / "artifacts"
            port = RecordingAcceptancePort()
            prepared = self.prepare(
                root,
                self.loop_payload(),
                items=[{"id": "api", "title": "API"}, {"id": "cli", "title": "CLI"}],
            )
            result = PipelineExecutor(
                port,
                virtual_inputs={"$issue": {"number": 20}},
            ).execute(prepared)

        self.assertTrue(result.succeeded, result.error)
        self.assertEqual(len(port.requests), 3)
        self.assertTrue(all(isinstance(request, StepExecutionRequest) for request in port.requests))

        top, api, cli = port.requests
        self.assertIs(type(top), type(api))
        self.assertEqual(top.step.runner, "codex")
        self.assertEqual(top.step.prompt, "prompts/plan.md")
        self.assertEqual(top.step.skill, "skills/plan.md")
        self.assertEqual(top.resolved_inputs[0].source, "$issue")
        self.assertEqual(top.expected_outputs[0].id, "plan")

        self.assertEqual(api.step.runner, "codex")
        self.assertEqual(api.step.prompt, "prompts/plan.md")
        self.assertEqual(api.step.skill, "skills/plan.md")
        self.assertEqual(api.resolved_inputs[0].source, "$loop_item")
        self.assertEqual(api.resolved_inputs[0].value["id"], "api")
        self.assertEqual(cli.resolved_inputs[0].value["id"], "cli")
        self.assertEqual(api.expected_outputs[0].id, "notes")
        self.assertNotEqual(api.expected_outputs[0].path, cli.expected_outputs[0].path)
        self.assertTrue(api.expected_outputs[0].path.is_relative_to(artifact_root))
        self.assertTrue(cli.expected_outputs[0].path.is_relative_to(artifact_root))
        self.assertNotEqual(
            api.expected_outputs[0].namespace.item_id,
            cli.expected_outputs[0].namespace.item_id,
        )
        self.assertEqual(api.expected_outputs[0].namespace.item_id, "api")
        self.assertEqual(cli.expected_outputs[0].namespace.item_id, "cli")

    def test_invalid_workflows_fail_before_execution_or_artifact_creation(self) -> None:
        """AC-5/7: the complete invalid-config matrix is fail-closed."""

        valid = json.loads(self.valid_fixture.read_text(encoding="utf-8"))
        undefined = deepcopy(valid)
        undefined["nodes"][0]["inputs"] = [  # type: ignore[index]
            {"name": "missing", "from": "artifact:missing.output"}
        ]

        duplicate = deepcopy(valid)
        duplicate["nodes"].append(deepcopy(duplicate["nodes"][0]))  # type: ignore[index]

        unbounded = deepcopy(valid)
        unbounded["nodes"][1].pop("max_items")  # type: ignore[index]

        nested = deepcopy(valid)
        nested["nodes"][1]["body"].append(  # type: ignore[index]
            deepcopy(nested["nodes"][1])
        )

        unsafe_path = deepcopy(valid)
        unsafe_path["nodes"][0]["outputs"][0]["path"] = "../escape.md"  # type: ignore[index]

        unknown_runner = deepcopy(valid)
        unknown_runner["nodes"][0]["runner"] = "unregistered"  # type: ignore[index]

        forward = self.top_level_payload(("first", "second"))
        forward["nodes"][0]["depends_on"] = ["second"]  # type: ignore[index]

        cycle = self.top_level_payload(("first", "second"))
        cycle["nodes"][0]["depends_on"] = ["second"]  # type: ignore[index]
        cycle["nodes"][1]["depends_on"] = ["first"]  # type: ignore[index]

        cases: tuple[tuple[str, dict[str, object], set[str]], ...] = (
            ("unknown-version", {**deepcopy(valid), "schema_version": "9.0"}, {"unknown_schema_version"}),
            ("duplicate-id", duplicate, {"duplicate_id"}),
            ("undefined-reference", undefined, {"undefined_reference"}),
            ("forward-dependency", forward, {"unreachable_dependency"}),
            ("dependency-cycle", cycle, {"dependency_cycle"}),
            ("unbounded-loop", unbounded, {"missing_field"}),
            ("nested-loop", nested, {"nested_loop"}),
            ("unsafe-path", unsafe_path, {"unsafe_path"}),
            ("unknown-runner", unknown_runner, {"unknown_capability"}),
        )

        for label, payload, expected_codes in cases:
            with self.subTest(case=label), tempfile.TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                artifact_root = root / "artifacts"
                port = RecordingAcceptancePort()
                with self.assertRaises(WorkflowConfigError) as context:
                    config = parse_workflow_config(payload)
                    prepared = prepare_workflow_run(
                        config,
                        repo_root=root,
                        artifact_root=artifact_root,
                    )
                    PipelineExecutor(port).execute(prepared)

                actual_codes = {diagnostic.code for diagnostic in context.exception.diagnostics}
                self.assertTrue(
                    expected_codes & actual_codes,
                    msg=f"{label} produced {actual_codes}, expected one of {expected_codes}",
                )
                self.assertEqual(port.requests, [])
                self.assertFalse(artifact_root.exists())

    def test_standard_config_matches_fixed_workflow_order_and_contract(self) -> None:
        """AC-6: bundled v1 config is an executable compatibility oracle."""

        config = self.load_combined_compatibility_config()
        self.assertEqual(
            [node.id for node in config.nodes],
            [
                "prototype_planning",
                "prototyping",
                "red_team_review",
                "solution_design",
                "work_breakdown",
                "plan_comprehension_check",
                "implementation",
                "review_fix_loop",
                "pull_request",
            ],
        )
        self.assertIsInstance(config.nodes[6], LoopConfig)
        self.assertEqual(
            [step.id for step in config.nodes[6].body],  # type: ignore[union-attr]
            [
                "implementation_coder",
                "implementation_reviewer_initial",
                "implementation_fix",
                "implementation_reviewer_final",
            ],
        )

        with tempfile.TemporaryDirectory() as tmpdir:
            artifact_root = Path(tmpdir) / "artifacts"
            items = [{"id": "WB-01"}, {"id": "WB-09"}]
            prepared = prepare_workflow_run(
                config,
                repo_root=self.repository_root,
                artifact_root=artifact_root,
                providers={"kelpie.work_items.v1": items},
                issue_snapshot={"number": 20},
                repo_instructions_snapshot="repository instructions",
                item_namespace="work-items",
            )
            port = RecordingAcceptancePort()
            result = PipelineExecutor(
                port,
                virtual_inputs={
                    "$issue": {"number": 20},
                    "$repo_instructions": "repository instructions",
                },
                controllers={
                    "implementation_review_v1": ImplementationReviewController(
                        registry=prepared.registry_snapshot,
                    )
                },
            ).execute(prepared)
            configured = characterize_configured_requests(
                result.requests,
                artifact_root=artifact_root,
            )
            legacy = characterize_legacy_workflow(
                artifact_root,
                item_ids=["WB-01", "WB-09"],
            )
            assert_workflow_parity(legacy, configured)

            work_breakdown_outputs = prepared.namespace_plan.for_instance(
                "nodes/work_breakdown"
            )
            self.assertEqual(
                {entry.relative_path for entry in work_breakdown_outputs},
                {"05-work-breakdown.md", "work_items.json"},
            )
            item_note_paths = {
                entry.relative_path
                for entry in prepared.namespace_plan.entries
                if entry.output_id == "notes"
            }

        self.assertTrue(result.succeeded, result.error)
        self.assertEqual(len(port.requests), 12)
        self.assertEqual(
            item_note_paths,
            {
                "work-items/WB-01/iterations/0000/coder/06-implementation-notes.md",
                "work-items/WB-01/iterations/0001/fix/06-implementation-notes.md",
                "work-items/WB-09/iterations/0000/coder/06-implementation-notes.md",
                "work-items/WB-09/iterations/0001/fix/06-implementation-notes.md",
            },
        )

    def test_standard_workflow_is_split_at_work_items_handoff(self) -> None:
        planning = load_workflow_config(self.standard_config_path)
        execution = load_workflow_config(self.execution_config_path)

        self.assertEqual(
            [node.id for node in planning.nodes],
            [
                "prototype_planning",
                "prototyping",
                "red_team_review",
                "solution_design",
                "work_breakdown",
                "plan_comprehension_check",
            ],
        )
        self.assertEqual(
            [node.id for node in execution.nodes],
            ["implementation", "review_fix_loop", "pull_request"],
        )
        self.assertIsInstance(execution.nodes[0], LoopConfig)
        self.assertEqual(execution.nodes[0].source.source, "$work_items")  # type: ignore[union-attr]

    def test_declarative_workflow_does_not_contain_runner_commands(self) -> None:
        """AC-8: workflow structure and runner command resolution stay separate."""

        raw_config = json.loads(self.standard_config_path.read_text(encoding="utf-8"))

        def keys(value: object) -> list[str]:
            if isinstance(value, dict):
                result: list[str] = []
                for key, child in value.items():
                    result.append(key)
                    result.extend(keys(child))
                return result
            if isinstance(value, list):
                return [key for child in value for key in keys(child)]
            return []

        self.assertFalse(
            {"command", "command_template", "callable", "shell"} & set(keys(raw_config))
        )

        runner = RunnerConfig(name="codex", command_template=["codex", "exec", "-"])
        resolver = RunnerResolver({"codex": runner}, default_name="codex")
        adapter = RunnerResolverCapabilityAdapter(resolver)
        snapshot = adapter.snapshot("repository_issue")
        resolved = adapter.resolve("codex", phase="plan", step_name="plan")

        self.assertNotIn("command_template", snapshot.runners["codex"].as_dict())
        self.assertEqual(resolved.command_template, ["codex", "exec", "-"])
        self.assertIn("codex", default_capability_registry().runners)


if __name__ == "__main__":
    unittest.main()
